@echo off
echo Running git init...
git init
echo Removing old remote (if any)...
git remote remove origin
echo Adding new remote...
git remote add origin https://github.com/vraj1091/RAG_chagtbot_1.git
echo Adding files...
git add .
echo Committing...
git commit -m "Initial commit"
echo Setting branch...
git branch -M main
echo Pushing...
git push -u origin main
echo Done.
